merge_queue:
  mode: serial

queue_rules:
  - name: vm2 draftbot current revalidation
    batch_size: 1
    max_checks_retries: 1
    queue_conditions:
      - base = main
      - title = VM2_DRAFTBOT_CURRENT_0928
    merge_conditions:
      - check-success = vm2-draftbot-hold
    merge_method: merge

commands_restrictions:
  queue:
    conditions:
      - sender-permission >= write

pull_request_rules: []
